Redshift dependent SED
cosmiclens/forward pull request #6
Opened 2019-10-31 12:07 UTC by jucordero

Implemented a redshift dependent model for the SED, using a linear combination of template SED with coefficients drawn from a Dirichlet distribution to address #2

2019-10-31 13:48 UTC, itrharrison requested changes

2019-10-31 13:48 UTC, itrharrison commented on forward/sed.py
> +    return np.power(alpha_0, 1-(z/z1)) * np.power(alpha_1, (z/z1))
Can you change this to e.g.
`dirichlet_alphas = np.power(alpha_0, 1-(z/z1)) * np.power(alpha_1, (z/z1))`
`return dirichlet_alphas`
as this makes debugging easier.

2019-10-31 13:48 UTC, itrharrison commented on forward/sed.py
> +    ci = np.random.dirichlet(alphas)
`ci` needs to have dimensions of number of templates.
Here, has dimensions of number of redshifts passed to `alphas`.

2019-10-31 14:37 UTC, jucordero commented on forward/sed.py
> +    return np.power(alpha_0, 1-(z/z1)) * np.power(alpha_1, (z/z1))
Done, should appear in new commits

2019-10-31 14:39 UTC, jucordero commented on forward/sed.py
> +    ci = np.random.dirichlet(alphas)
It now has `ci.shape = (nz, nt)`, number of redshifts times number of templates.
The whole function now should return an array of dimensions nz, nlambda

2019-11-04 09:35 UTC, itrharrison approved these changes

2019-11-04 09:35 UTC, merged